Bluecurrent integration
bluecurrent/core pull request #1
Opened 2021-10-18 07:12 UTC by Floris272

## Breaking change

## Proposed change

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New integration (thank you!)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast homeassistant tests`)
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

If the code communicates with devices, web services, or third-party tools:

- [ ] The [manifest file][manifest-docs] has all fields filled out correctly.  
      Updated and included derived files by running: `python3 -m script.hassfest`.
- [ ] New or updated dependencies have been added to `requirements_all.txt`.  
      Updated by running `python3 -m script.gen_requirements_all`.
- [ ] For the updated dependencies - a link to the changelog, or at minimum a diff between library versions is added to the PR description.
- [ ] Untested files have been added to `.coveragerc`.

The integration reached or maintains the following [Integration Quality Scale][quality-scale]:

- [ ] No score or internal
- [ ] 🥈 Silver
- [ ] 🥇 Gold
- [ ] 🏆 Platinum

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/core/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+-label%3Awaiting-for-upstream+sort%3Acreated-desc+review%3Anone

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[manifest-docs]: https://developers.home-assistant.io/docs/en/creating_integration_manifest.html
[quality-scale]: https://developers.home-assistant.io/docs/en/next/integration_quality_scale_index.html
[docs-repository]: https://github.com/home-assistant/home-assistant.io

2021-10-18 14:19 UTC, florianhumblot requested changes

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/translations/nl.json
> +            "unknown": "Onverwachte fout"
Moeten de andere strings nog een vertaling krijgen of is dit een work-in-progress?

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/__init__.py
> +    await asyncio.sleep(1)
Meestal zijn sleeps niet wenselijk halverwege een function-call, is deze nodig of was dit test-code?

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/__init__.py
> +async def async_setup_entry(hass: HomeAssistant, config_entry: ConfigEntry):
Op sommige plekken gebruik je wel return-types maar hier niet. Moet hier ook nog `-> Bool ` achter staan?

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/__init__.py
> +    def __init__(
Dit kan denk ik op een regel zonder dat je de limiet van PEP8 overschrijdt.

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/__init__.py
> +    """Define a class to to connect to the websocket."""
"a class" en "the websocket" zijn wel vrij vaag. 
Misschien een uitgebreidere definitie zoals bijvoorbeeld:
"Class that manages a single connection with Blue Current's websocket API"

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/__init__.py
> +        self.client = client
is het de bedoeling dat `self.client` en `self.charge_points`  wel public zijn terwijl `self._hass` en `self._config`  dat niet zijn?

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/__init__.py
> +        self.client = client
Daarnaast is het qua consistentie mooi als je overal type hints gebruikt i.p.v. alleen bij `self.charge_points`

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/__init__.py
> +        # await self.client.connect(token)
Is deze regel code nog nodig?

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/__init__.py
> +    """Define a base charge point entity entity."""
entity entity?

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/const.py
> +    "voltage 1": {
Voor alle velden hier geldt dat het niet `voltage n` is maar `Voltage phase n` en `current phase n` als je het correct wil verwoorden :)

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/const.py
> +    # "vehicle status": {CONF_NAME: "vehicle status", CONF_ICON: "mdi:car"},
is dit comment blok nog nodig?

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/manifest.json
> +  "requirements": [],
Zou de `bluecurrentapi` package niet nodig zijn als requirement of als dependency?

2021-10-18 14:19 UTC, florianhumblot commented on homeassistant/components/bluecurrent/sensor.py
> +        for sensor in SENSOR_TYPES.items():
Misschien is een `map` functie hier netter dan een for_loop

2021-10-18 14:37 UTC, Floris272 commented on homeassistant/components/bluecurrent/translations/nl.json
> +            "unknown": "Onverwachte fout"
gefixt

2021-10-18 14:44 UTC, Floris272 commented on homeassistant/components/bluecurrent/__init__.py
> +    await asyncio.sleep(1)
Die is nodig omdat anders de data te laat binnen komt en dan worden er geen platforms aangemaakt. de sleep zou wel misschien nog korter kunnen.

2021-10-18 14:48 UTC, Floris272 commented on homeassistant/components/bluecurrent/const.py
> +    "voltage 1": {
Ja klopt dit moet nog worden aangepast. Ik ga met Gert Jan en Niels woensdag overleggen hoe we de api gaan aanpassen dus ik heb gewacht met de alle goede benamingen

2021-10-18 14:49 UTC, Floris272 commented on homeassistant/components/bluecurrent/manifest.json
> +  "requirements": [],
Ja klopt maar de package staat nog niet online dus ik wacht daar nog mee

2021-10-20 12:17 UTC, Floris272 commented on homeassistant/components/bluecurrent/__init__.py
> +async def async_setup_entry(hass: HomeAssistant, config_entry: ConfigEntry):
gefixt

2021-10-20 12:17 UTC, Floris272 commented on homeassistant/components/bluecurrent/__init__.py
> +    """Define a class to to connect to the websocket."""
gefixt

2021-10-20 12:17 UTC, Floris272 commented on homeassistant/components/bluecurrent/__init__.py
> +    """Define a base charge point entity entity."""
gefixt

2021-10-20 12:22 UTC, Floris272 commented on homeassistant/components/bluecurrent/__init__.py
> +        self.client = client
het eerste klopt, voor de type hints: ze staan al in de init() dus het lijkt me overbodig

2021-10-20 12:22 UTC, Floris272 commented on homeassistant/components/bluecurrent/__init__.py
> +        # await self.client.connect(token)
gefixt

2021-10-20 12:24 UTC, Floris272 commented on homeassistant/components/bluecurrent/sensor.py
> +        for sensor in SENSOR_TYPES.items():
Ik heb naar de map functie gekeken maar ik heb niet gevonden hoe ik er naast de sensor types de connector en evse_id aan mee geef.

2021-10-20 12:25 UTC, Floris272 commented on homeassistant/components/bluecurrent/__init__.py
> +    def __init__(
Het wordt zo neergezet door de formatter (Black)

2021-10-25 08:23 UTC, florianhumblot commented on homeassistant/components/bluecurrent/__init__.py
> +        self.client = client
Hoewel ze al in de `init` staan, is het handig om ze hier ook toe te voegen. 
De reden hiervoor is dat type-hints scoped zijn, dus de hint geldt alleen voor de parameters die worden meegegeven aan je `init` functie. 
Als je type-hits toevoegd aan de`self._config` bijvoorbeeld, dan krijg je overal waar je er iet mee doet de typehint terug.

2021-11-19 15:37 UTC, closed without merging